---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ahren.
--- DateTime: 2023/08/28 18:39
--- 被动buff技能触发(被攻击时)

local utility = nil

---@class SkillBeAttached
local m = {

}

local luaConfig = LuaConfig

---重新加载脚本事件
function m.Init()
    utility = Utility
    luaConfig = LuaConfig
    
 end
 GameManager.ScriptLoadedEvent:addAction(m.Init)

---冻汽反射
---@param player Player 被攻击者
---@param spirit Spirit 攻击者
---@param damage number 伤害值
---@return number 返回伤害值
local function HandeleColdReflection(player, spirit, damage, buffIdx)
    ---如果被怪物攻击不处理
    if spirit:IsMonster() then
        return damage
    end

    local otherPlayer = spirit:ToPlayer()
    local buffDB = luaConfig.buffConfig[buffIdx]
    ---@type Skill
    local skill = player:GetSkillByName_US(buffDB.name)
    local level = skill:Level()

    local otherSkillDB = luaConfig.skillConfig[skill:Idx()]
    ---减攻速概率、减攻速百分比
    local proNum1 = otherSkillDB.attribute1[level]
    local val1 = otherSkillDB.attribute2[level]

    ---冰冻概率、冰冻时长
    local proNum2 = otherSkillDB.attribute3[level]
    local val2 = otherSkillDB.attribute4[level]

    local ranNum = Random(100)
    ---命中减速buff
    if ranNum < proNum1 then
        if not otherPlayer:HasSkillBuff(53) then
            otherPlayer:SetNumber("BUFF技能_冻汽反射", val1, false)
            otherPlayer:AddBuffByIdx(53, 30, false)
        end
    end

    ---命中冰冻buff
    if ranNum < proNum2 then
        if not otherPlayer:HasSkillBuff(54) then
            otherPlayer:AddBuffByIdx(54, val2, false)
        end
    end

    return damage
end

---盾牌反射
---@param player Player 被攻击者
---@param spirit Spirit 攻击者
---@param damage number 伤害值
---@return number 返回伤害值
local function HandeleShieldReflection(player, spirit, damage, buffIdx)
    local buffDB = luaConfig.buffConfig[buffIdx]
    ---@type Skill
    local skill = player:GetSkillByName_US(buffDB.name)
    local level = skill:Level()
    local pr = player:GetAttr(emBaseAttr.PR)

    local spirits = Game:GetNearbySpirits(player:SceneName(), player:PosX(),  player:PosY(), 2)
    ---物理反弹值(受到的伤害 * prDamage) 
    local prDamage = math.floor(damage * pr / 100)
    ---获取到C++的智能指针
    local spiritPtr = player:GetSpiritPtr()

    local playerPtr = player:GetPlayerPtr()

    for i = 1, #spirits, 1 do
        ---@type Spirit
        local currentSpirit = spirits[i]

        if currentSpirit:Id() == player:Id() then
            goto continue
        end
        if currentSpirit:IsPlayer() then
            local otherPlayer = currentSpirit:ToPlayer()
            if utility.IsSameSide(player, spirit:ToPlayer()) then
                goto continue
            end
            otherPlayer:SubHP(prDamage, spiritPtr)
            player:ShowDamage(otherPlayer:Uid(), prDamage, 0)
        elseif currentSpirit:IsMonster() then
            local otherMonster = currentSpirit:ToMonster()
            otherMonster:SubHP(prDamage)
            otherMonster:TakesDamage(playerPtr, prDamage)
            player:ShowDamage(otherMonster:Uid(), prDamage, 0)
        end
        
        ::continue::
    end
    return damage
end

local mapSkillBuff = {
    [1] = {
        idx = 52,
        callBack = HandeleColdReflection
    },
    [2] = {
        idx = 45,
        callBack = HandeleShieldReflection
    }
}

---被攻击时处理身上的buff
---返回最小伤害数值
---@param player Player 被攻击者
---@param spirit Player 攻击者
---@param damage number 伤害值
---@return number 返回伤害值
function m.HandeleSkillBuff(player, spirit, damage)
    for index, value in ipairs(mapSkillBuff) do
        if player:HasSkillBuff(value.idx) then
            local _damage = value.callBack(player, spirit, damage, value.idx)
            if _damage < damage  then
                damage = _damage
            end
        end
    end
    return damage
end



SkillBeAttached = m
return m