---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ahren.
--- DateTime: 2023/08/10 16:26
---   全局定时器触发文件
---   处理所有配置的定时任务触发

local m = {}

local luaConfig

---脚本初始化完成回调
function m.Init()
    luaConfig = LuaConfig
end


---定时任务触发
---@param idx number 定时任务配置序号
function m.OnTimerInvoker_1(idx)
    local gTimerDB = luaConfig.globalTimer[idx]

    local date_time = os.date("%Y-%m-%d %H:%M:%S", os.time())
    log(string.format("OnTimerInvoker_1 DateTime %s Name %s", date_time, gTimerDB.name))
end

---定时任务触发
---@param idx number 定时任务配置序号
function m.OnTimerInvoker_2(idx)
    local gTimerDB = luaConfig.globalTimer[idx]
    
    local date_time = os.date("%Y-%m-%d %H:%M:%S", os.time())
    log(string.format("OnTimerInvoker_1 DateTime %s Name %s", date_time, gTimerDB.name))
end







GlobalTimerManager = m
return m