---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ahren.
--- DateTime: 2023/08/10 16:26
---   全局定时器触发文件
---   处理所有配置的定时任务触发

local m = {}

local luaConfig

---脚本初始化完成回调
function m.Init()
    luaConfig = LuaConfig
end


---定时任务触发
---@param idx number 定时任务配置序号
function m.OnTimerInvoker_1(idx)
    ---如果不是主场景 不处理
    if not Game:IsMainScene() then
        return
    end
    Game:SetNumber("全局变量_开区分钟数", Game:GetNumber("全局变量_开区分钟数", 0) + 1, true)
end

---定时任务触发
---@param idx number 定时任务配置序号
function m.OnTimerInvoker_2(idx)
    ---如果不是主场景 不处理
    if not Game:IsMainScene() then
        return
    end
    Game:SetNumber("全局变量_开区天数", Game:GetNumber("全局变量_开区天数", 0) + 1, true)
    log("OnTimerInvoker_2")
end







GlobalTimerManager = m
return m